# -*- coding: utf-8 -*-
"""Task1_GirlScript_Foundation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TNRRc4mcF_ACBl6cjteeWc9PUhxF0EdN

## **Task1 : GirlScript Foundation**

# ***Author : Rahul Kale***

***1) Python Program to use all Arithmatic Operators.***
"""

# Addition
a = 88
b = 10
c = a+b
print(c)

# Subtraction
a = 45
b = 23
print(a-b)

# Multiplication
a = 24
b = 19
print(a*b)

# Division
a = 64
b = 4
print(a/b)

# Modulus
a = 21
b = 2
print(a % b)

# Quotient
a = 48
b = 5
print(a//b)

# Exponent
a = 8
b = 3
print(a**b)

"""***2) Python Program to use all Assignment Operators.***"""

a = 88
a += 10
print(a)

a = 88
a -= 10
print(a)

a = 88
a *= 10
print(a)

a = 88
a /= 10
print(a)

a = 95
a %= 10
print(a)

a = 88
a //= 10
print(a)

a = 4
a **= 3
print(a)

"""***3) Python Program to use all Comparison Operators.***"""

# Equal to
a = 8
print(a == 8)

# Equal to
a = 56
print(a == 6)

# Not Equal to
a = 8
print(a != 6)

# Greater than 
a = 12
b = 28
if a>b:
  print("a is greater than b", a)
else:
  print("b is greater than a", b)

# Less than 
a = 34
b = 15
if a<b:
  print("a is less than b", a)
else:
  print("b is less than a", b)

a = 34
b = 15
print(a>=b)

a = 34
b = 15
print(a<=b)

a = 4
b = 14
print(a>=b)

a = 34
b = 54
print(a<=b)

"""***4) Python Program to use all Identity Operators.***"""

a = "python"
a = b
print(a is b)

a = "python"
a = b
print(a is not b)

"""***5) Python Program to use all Membership Operators.***"""

r = "tableau"
print("tableau" in r)

r = "tableau"
print("python" not in r)

"""***6) Python Program to find maximum of two numbers.***"""

a = 45
b = 64
print(max(a,b))

"""***7) Python Program for Simple Interest.***"""

# Method-1
P = 1000  
R = 5
T = 2
# SI = Simple Interest
SI = (P*R*T)/100
print(SI)

# Method-2
P = int(input("Enter the value of P"))
R = int(input("Enter the value of R"))
T = int(input("Enter the value of T"))
SI = (P*R*T)/100
print(SI)

P = 1000  
R = 5
T = 2
# CI = Compound Interest
CI =  P * (pow((1 + R / 100), T))
print(CI)

"""***8) Python Program to find area of circle.***"""

import math
R = float(input('Enter the radius of the circle :'))
area = math.pi * R * R
print("Area of the circle is : %.2f" %area)



"""***9) Python Program for Implicit and Explicit type Conversion***"""

# Implicit type Converison
impli_int = 68
impli_float = 2.3
impli_add = impli_int + impli_float
print(impli_add)
print(type(impli_add))

# Explicit type Conversion
expli_str = "578"
expli_int = 5
expli_str = int(expli_str)
expli_add = expli_str + expli_int
print(expli_add)
print(type(expli_add))

"""### **!! Thank You !!**"""